/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'STM32F103' 
 * Target:  'STM32F103' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::Compiler&ARM Compiler:I/O:STDIN&Breakpoint@1.2.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
#define RTE_Compiler_IO_STDIN_BKPT      /* Compiler I/O: STDIN Breakpoint */


#endif /* RTE_COMPONENTS_H */
